language: python
python:
  - '2.6'
  - '2.7'
install:
  - sudo mkdir /etc/unbound
  - sudo -E chown $USER /etc/unbound
  - python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  on:
    tags: true
    branch: master
  user:
    secure: Vtvi3FeyeeaXnhXsGbOSBPcINyLt4sXKwzvGv81OSxF8jNGCv3Z6lB9XAWde3/x/KxBihnub8ylxQky6WT46tmDI7vPokDa3XuPRvwZNucMArzl+P3f2h0IDIo4ixN32xC2Jf3+i4Dwzb52iWiTX3Q434hod7x8pfLbs4sw1vl4=
  password:
    secure: tMhFS3hoZlUwqCv2BOHrj1MIUY7DjAsJ4V8y6aYXwQ89+UuGityvE1MkTAOUEuVCeKlrmztV1rBtRjrHXJYLo8dnlasOUZL6D7cKhCQZS7LqDTSsYNfl04hdCTPJfnPZWtd3sRiEaw3thvIl0h2pbNC+Dg38lsc2bLXEfzfnTMs=
