language: python
python:
  - "2.6"
  - "2.7"
install:
  - sudo mkdir /etc/unbound
  - sudo -E chown $USER /etc/unbound
  - python setup.py install
script: python setup.py test

deploy:
  provider: pypi
  user:
    secure: "COGYNLr4rUoeaPgJK/Vvj5ZXmoVovhfoHjKS8G07hJEDW2S5jTOTpwNyO/k8SAnhsmXv+Inium4xhflm4Cc/zrNZZJ8wQe+2kEqLFKlo00oHa6KkVbpe30Etbl2vitaHwA+YMlhmu4szJEbBRShlYwTW/uumGzEBsFrkOjeIpCg2DaZJRIiNC3VtRUDqSom/lwd0lZrudVRsNtyUMZ7MxnvRQ/0d1gfqiQOFni5EcbkyRB0UjSwAfwsjJjo1H5qfNB8Dh3LvhggkyEsuDMciYT/+dT5elYQCsgHUUazSjV2VGbBsLhK9xXaoaqRsSuFt3O/PXtlb0SB3bOaZC0oqjahF95ZmIRPFmc6E/hEqzpnOcdVnY+PcLxzv0jPEckJya2PHhlvfRHLLCoRtWvZTnlJYnjVPUp5AbbQaRyB0KZlhMxEMZAa7ajf+YZ1cdS/zQrSVTvbVrURsDMmop2wPjQ6zUgvGw97nFNqysDbFeJNWOOPdnbWoFckLBKk6XjYHg62fb/uQzDnMkaylAnVibdB5YpkScz0H4Hy4LgJKfEyXCimaZW/xYRLFnNM4M3FAVyCjCmfBh+DKM0j+ZuitGYNJjdimbO5IQrgSwMdYO+b6M55Qr7CIP110kqY4z/9pdz8xHeHanemLnKVTlYBly/VPgXjAwZWOPhXMqDXfCPA="
  password:
    secure: "IftLUWaGIf9pKzyXCjqgoz/CeA7ak/2rKjrN3EsTTValFB/Mm4C+rxRRgUjW763GKnvi/I62dKl2m+tMINuNHQoUhxmO1wYi1RRgR8pY77qME7ZcfeeTW51FrcXrO9kCQc8k6FKkTETVi58CBrfjp/KyDA67kIP1c8cAdE5j25UvAnlsZNlxolAjqe/osKqmrl3MlpjVOemEQyrlbmChl9b4pUNDA1PRkVBndJWNSJHjSAmwdarGV/7GkL0RYyShAOaYAOjvAw7nKtDXegkz2pcR+fOMVanuJrOkRBQWyVAlawtpn31ezKylox0gbIjkSrjcRhuEtfGAMq37q4KAtCTH3mxfflhQkLi8C/CW7gRZKqzFTjRhFi9PBDIofZN8nU8TAd1B+ojNYHm1f7lIuB5HviJwKm6JHgophfeTQ/9l97O02M6ZtY2iqpaBdNdDoXldHzp4h3pu7LzdI+NIoL5sv+snsioKR+WmRb+7q/z+fJzwghUFEMQ/vJIqpNCQHJNA9HnORPC70LtKCDT3Lc8MTj05P7Yz1nU85rznsBx3hkecauktGycM17cpjFw+T0F276Nk6Pr0DcLOcE9GW8VoXf4FKIbTkw0oq8HJkK/b1FZ7uOyCd+WdfBeJJA5xR0WZlDXtWKJJ86+UFzkx/rAXYwrXLybTlWbbfoyP+eU="
  on:
    tags: true
    branch: master
